

services:
  web:
    build: .
    container_name: linux-agent-app
    ports:
      - "5000:5000"
      - "5001:5000"
      - "5002:5000"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db2
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  
